// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtWMxqOWZ4svpHpVaC0SOgG5YHXmqZIWs',
    appId: '1:271856068395:web:e99bf24dc6df707cc5476e',
    messagingSenderId: '271856068395',
    projectId: 'votingapp-8f3c9',
    authDomain: 'votingapp-8f3c9.firebaseapp.com',
    storageBucket: 'votingapp-8f3c9.firebasestorage.app',
    measurementId: 'G-V1J1G1XDFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGEBW3a26dSUrh6o92KFptxZ3gefmxxuw',
    appId: '1:271856068395:android:30dfe2d9ebc67189c5476e',
    messagingSenderId: '271856068395',
    projectId: 'votingapp-8f3c9',
    storageBucket: 'votingapp-8f3c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJg0e-bdl_bFfJKlSj119tkIuZthQg1tQ',
    appId: '1:271856068395:ios:5ceaea1c89675c63c5476e',
    messagingSenderId: '271856068395',
    projectId: 'votingapp-8f3c9',
    storageBucket: 'votingapp-8f3c9.firebasestorage.app',
    iosBundleId: 'com.example.votingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJg0e-bdl_bFfJKlSj119tkIuZthQg1tQ',
    appId: '1:271856068395:ios:5ceaea1c89675c63c5476e',
    messagingSenderId: '271856068395',
    projectId: 'votingapp-8f3c9',
    storageBucket: 'votingapp-8f3c9.firebasestorage.app',
    iosBundleId: 'com.example.votingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtWMxqOWZ4svpHpVaC0SOgG5YHXmqZIWs',
    appId: '1:271856068395:web:1984ce5d40086c0ac5476e',
    messagingSenderId: '271856068395',
    projectId: 'votingapp-8f3c9',
    authDomain: 'votingapp-8f3c9.firebaseapp.com',
    storageBucket: 'votingapp-8f3c9.firebasestorage.app',
    measurementId: 'G-B8BWBFWV0L',
  );
}
